name: Sync and Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: Creates output
        run: sh ./build.sh

      - name: Checkout destination repository
        uses: actions/checkout@v2
        with:
          repository: SNXWXH/KT-Vicddory-FE
          token: ${{ secrets.SNXWXH_GITHUB_KEY }}
          path: destination_repo

      - name: Copy output to destination
        run: |
          rsync -av --delete output/ destination_repo/

      - name: Commit and Push changes
        working-directory: destination_repo
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ secrets.SNXWXH_ACCOUNT_EMAIL }}"
          git add .
          git commit -m "${{ github.event.commits[0].message }}"
          git push origin main
